name: Deploy to dev Workflow

on:
  issue_comment:
    types: [created]

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/dev')
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set Environment Variables #Environment means dev-01, dev-02, dev-03, staging
        env:
          GITHUB_COMMENT: ${{github.event.comment.body}}
        id: set-environment-variables
        run: |
          echo "GITHUB_COMMENT is: $GITHUB_COMMENT"
          for i in $GITHUB_COMMENT
          do
            if [[ ${i} =~ ^env\=.* ]]
            then
              env=$(echo $i | awk -F '=' '{print $2}')
            fi
          done
          echo "env: $env"
          echo "::set-output name=env::${env}"

      - name: deploy to dev
        env:
          env: ${{steps.set-environment-variables.outputs.env}}
        run: |
          if [ -z "$env" ]
          then
                echo "\$env is empty"
          else
                echo "\$env is NOT empty"
          fi
